name: Continious Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  test:
    needs: [ build ]
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - run: dotnet tool install -g dotnet-reportgenerator-globaltool
    - run: dotnet tool install dotnet-coverage
    - uses: paambaati/codeclimate-action@v3.2.0
      env:
        CC_TEST_REPORTER_ID: c446fec35062589f55dd444094d515bd29e715e771e9e2c969fcf340017833cc
      with:
        coverageCommand: dotnet coverage collect dotnet test --output ./code-coverage/output --output-format cobertura && reportgenerator -reports:./code-coverage/output.cobertura.xml -targetdir:"./code-coverage" -reporttypes:Clover -assemblyfilters:-MinimalApi;-Humanizer
        coverageLocations: ${{github.workspace}}/code-coverage/Clover.xml:clover
  analyze:
    needs: [ build ]
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
